### ISSUE TITLE
How to add the cli args?

### ISSUE THREAD

**Issue by Fonta1n3** [Start9Labs/c-lightning-http-plugin#2]
Total newb question: 

I have tried setting `rpc-user` `rpc-password` `rpc-port` as cli args when building the library, adding them to the lightning conf and passing them as `lightningd` cli args, all of which return errors. How/where can you specify these params? I ended up just hardcoding them in the source code and rebuilding which worked but I would like to more easily allow users to customize this.

**Comment by dr-bonez** [comment]
so its `http` not `rpc`. Also there was a mistake in the readme: it should be `pass` instead of `password`. Will reopen this if you are still having issues, but I have tested it locally and it is working as intended.
