### ISSUE TITLE
Allow binding on 0.0.0.0

### ISSUE THREAD

**Issue by NicolasDorier** [Start9Labs/c-lightning-http-plugin#3]
Planning to use it in our c-lightning docker image, but because it binds to 127.0.0.1, can't expose it outside the container.

**Comment by ProofOfKeags** [comment]
How are you encrypting the link? The reason we bind to local host is because we use Tor. We could make this configurable, but make sure to do Auth/encryption on the link.

**Comment by NicolasDorier** [comment]
Tor is in a separate container than C-Lightning. This is process isolation, all container in a docker network are isolated from the host, you expose only the port to the other docker containers, not to the host.

**Comment by dr-bonez** [comment]
@NicolasDorier you are 100% right, changed the api. Required a major version change. Will close when merged.
